[package]
name = "graphite-store"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
graphite-model.workspace = true
cozo.workspace = true
thiserror.workspace = true

[dev-dependencies]
blake3.workspace = true
tempfile = "3"
graphite-extract-python = { path = "../extract-python" }
walkdir = "2"
