[package]
name = "graphite-extract-python"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
graphite-model.workspace = true
blake3.workspace = true
tree-sitter = "0.24"
tree-sitter-python = "0.23"
streaming-iterator = "0.1"

[dev-dependencies]
serde_json.workspace = true
walkdir = "2"
